"""
ResolveAI – 3D LUT Generator

Generates standard .cube 3D LUT files from transform functions.
These LUTs can be applied to clips in DaVinci Resolve via the scripting API.

The .cube format is an industry standard supported by Resolve, Premiere,
Final Cut Pro, and virtually every color grading application.
"""

import os
import numpy as np
from typing import Callable, Optional
from datetime import datetime

from config import LUT_SIZE, LUTS_DIR, LUT_TITLE_PREFIX


def generate_3d_lut(
    transform_fn: Callable,
    lut_size: int = None,
    title: str = None,
    output_path: str = None,
    clip_name: str = "",
) -> str:
    """
    Generate a .cube 3D LUT file from a color transform function.
    
    The LUT is a 3D grid where each point maps an input RGB value
    to an output RGB value via the transform function.
    
    Args:
        transform_fn: Function that takes an RGB array [R,G,B] (0–255)
                      and returns a transformed RGB array [R,G,B] (0–255).
        lut_size: Grid size (default: 33 → 33×33×33 = 35,937 entries).
        title: Title string for the LUT file header.
        output_path: Where to save the .cube file. Auto-generated if None.
        clip_name: Clip name for auto-generated filename.
    
    Returns:
        Absolute path to the generated .cube file.
    """
    if lut_size is None:
        lut_size = LUT_SIZE

    if title is None:
        title = f"{LUT_TITLE_PREFIX}_{clip_name}" if clip_name else LUT_TITLE_PREFIX

    if output_path is None:
        # Auto-generate filename
        safe_name = "".join(c if c.isalnum() or c in "_-" else "_" for c in clip_name)
        timestamp = datetime.now().strftime("%H%M%S")
        filename = f"resolveai_{safe_name}_{timestamp}.cube"
        output_path = os.path.join(LUTS_DIR, filename)

    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    print(f"[ResolveAI] Generating {lut_size}³ 3D LUT: {os.path.basename(output_path)}")

    # Build the 3D LUT grid
    # The .cube format iterates: R changes fastest, then G, then B
    lines = []
    lines.append(f"TITLE \"{title}\"")
    lines.append(f"# Generated by ResolveAI on {datetime.now().isoformat()}")
    lines.append(f"LUT_3D_SIZE {lut_size}")
    lines.append(f"DOMAIN_MIN 0.0 0.0 0.0")
    lines.append(f"DOMAIN_MAX 1.0 1.0 1.0")
    lines.append("")

    total_points = lut_size ** 3
    processed = 0

    for b_idx in range(lut_size):
        for g_idx in range(lut_size):
            for r_idx in range(lut_size):
                # Normalize grid indices to 0–255
                r_in = (r_idx / (lut_size - 1)) * 255.0
                g_in = (g_idx / (lut_size - 1)) * 255.0
                b_in = (b_idx / (lut_size - 1)) * 255.0

                # Apply transform
                rgb_in = np.array([r_in, g_in, b_in], dtype=np.float64)
                try:
                    rgb_out = transform_fn(rgb_in)
                except Exception:
                    rgb_out = rgb_in  # Identity fallback

                # Convert back to 0–1 range for .cube format
                r_out = np.clip(rgb_out[0] / 255.0, 0.0, 1.0)
                g_out = np.clip(rgb_out[1] / 255.0, 0.0, 1.0)
                b_out = np.clip(rgb_out[2] / 255.0, 0.0, 1.0)

                lines.append(f"{r_out:.6f} {g_out:.6f} {b_out:.6f}")

                processed += 1

    # Write the file
    with open(output_path, "w") as f:
        f.write("\n".join(lines))
        f.write("\n")

    file_size_kb = os.path.getsize(output_path) / 1024
    print(f"[ResolveAI] LUT saved: {output_path} ({file_size_kb:.0f} KB)")
    return output_path


def generate_identity_lut(lut_size: int = None, output_path: str = None) -> str:
    """
    Generate an identity (no-op) LUT for testing.
    
    Every input maps to itself. Useful for verifying the LUT pipeline works.
    """
    def identity(rgb: np.ndarray) -> np.ndarray:
        return rgb

    if output_path is None:
        output_path = os.path.join(LUTS_DIR, "identity.cube")

    return generate_3d_lut(identity, lut_size=lut_size, title="Identity",
                           output_path=output_path)


def generate_lut_with_normalization(
    normalization_cdl: dict,
    creative_transform_fn: Callable,
    lut_size: int = None,
    clip_name: str = "",
    output_path: str = None,
) -> str:
    """
    Generate a single LUT that combines normalization + creative grade.
    
    This is the key function: it bakes both the exposure/WB correction
    AND the creative color transfer into one LUT, so we only need
    one node in Resolve.
    
    Args:
        normalization_cdl: Dict with slope, offset, power from normalizer.
        creative_transform_fn: Transform function from transfer.py.
        lut_size: Grid size.
        clip_name: For filename.
        output_path: Override output path.
    
    Returns:
        Path to generated .cube file.
    """
    slope = normalization_cdl.get("slope", (1.0, 1.0, 1.0))
    offset = normalization_cdl.get("offset", (0.0, 0.0, 0.0))
    power = normalization_cdl.get("power", (1.0, 1.0, 1.0))

    def combined_transform(rgb: np.ndarray) -> np.ndarray:
        # Step 1: Apply CDL normalization (exposure + WB)
        # CDL formula: output = (input * slope + offset) ^ power
        r = rgb[0] / 255.0  # Work in 0–1 for CDL
        g = rgb[1] / 255.0
        b = rgb[2] / 255.0

        r = np.clip((r * slope[0] + offset[0]), 0, 1) ** power[0]
        g = np.clip((g * slope[1] + offset[1]), 0, 1) ** power[1]
        b = np.clip((b * slope[2] + offset[2]), 0, 1) ** power[2]

        normalized_rgb = np.array([r * 255, g * 255, b * 255], dtype=np.float64)

        # Step 2: Apply creative transform
        result = creative_transform_fn(normalized_rgb)
        return result

    return generate_3d_lut(
        combined_transform,
        lut_size=lut_size,
        title=f"{LUT_TITLE_PREFIX}_combined_{clip_name}",
        clip_name=clip_name,
        output_path=output_path,
    )


def cleanup_old_luts(max_age_hours: int = 24):
    """Remove LUT files older than max_age_hours from the output directory."""
    import time

    if not os.path.isdir(LUTS_DIR):
        return

    cutoff = time.time() - (max_age_hours * 3600)
    removed = 0

    for filename in os.listdir(LUTS_DIR):
        if not filename.endswith(".cube"):
            continue
        filepath = os.path.join(LUTS_DIR, filename)
        if os.path.getmtime(filepath) < cutoff:
            try:
                os.remove(filepath)
                removed += 1
            except OSError:
                pass

    if removed > 0:
        print(f"[ResolveAI] Cleaned up {removed} old LUT files.")
